- name: Terminate EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no
      
  tasks:
    - name: Find EC2 Facts
      ec2_instance_facts:
        region: us-east-2
        filters:
          "tag:Name": gautam
      register: ec2_facts

    - name: Terminate EC2 server
      ec2:
        region: us-east-2
        instance_ids: "{{ item }}"
        state: 'absent'
      with_items: "{{ ec2_facts }}"
